---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: ssh-config-initializer
    files:
      - 45-config
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
