---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Toronto
  METALLB_LB_RANGE: 192.168.20.17-192.168.20.31
  METALLB_K8S_GATEWAY_ADDR: 192.168.21.53,fdd5:aa8:9535:21::53
  METALLB_INGRESS_ADDR: 192.168.21.80
  METALLB_SSH_ADDR: 192.168.21.22,fdd5:aa8:9535:21::22
