---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Toronto
  METALLB_LB_RANGE: 192.168.20.20-192.168.20.30
  METALLB_K8S_GATEWAY_ADDR: 192.168.20.30
  METALLB_INGRESS_ADDR: 192.168.20.29
