---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
      namespace: networking
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: k8s-gateway
            patch:
              - op: add
                path: /spec/ports/-
                value:
                  name: dns-tcp
                  port: 53
                  protocol: TCP
                  targetPort: dns-tcp
          - target:
              kind: Deployment
              name: k8s-gateway
            patch:
              - op: add
                path: /spec/template/spec/containers/0/ports/-
                value:
                  containerPort: 1053
                  name: dns-tcp
                  protocol: TCP
  values:
    fullnameOverride: k8s-gateway
    domain: ${SECRET_DOMAIN}
    ttl: 1
    service:
      type: LoadBalancer
      ipFamilyPolicy: PreferDualStack
      port: 53
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "bgp-dns.${SECRET_DOMAIN}"
        metallb.universe.tf/loadBalancerIPs: "${METALLB_K8S_GATEWAY_ADDR}"
        metallb.universe.tf/address-pool: routed
      externalTrafficPolicy: Local
